# Generated by Django 2.2 on 2019-04-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehical_type', models.CharField(choices=[('TRUCK', 'truck'), ('BUS', 'bus'), ('AIRPLANE', 'airplane')], max_length=1)),
                ('model_name', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('WORKING', 'working'), ('MAINTENANCEUS', 'maintenanceus')], max_length=1)),
            ],
        ),
    ]
